#!/usr/bin/env python
''' Command Line Interface for ttools_shm_fit '''
import argparse
from tractools.cli.csd import csd

if __name__ == "__main__":

    # Parser
    parser = argparse.ArgumentParser(description=("Computes Spherical "
                                                  "Harmonic coeficients"))

    parser.add_argument('dwi', type=str, help='Diffusion Weighted Image')

    parser.add_argument('bvals', type=str, help='bvals file')

    parser.add_argument('bvecs', type=str, help='bvecs file')

    parser.add_argument('-out_shm', type=str, help='filename for output shm')

    parser.add_argument('-roi_center', type=int, nargs='+', default=None,
                        help='Voxel where to compute response during fitting')

    parser.add_argument('-roi_radius', type=int, default=10,
                        help='Radius of sphere around roi_center')

    parser.add_argument('-fa_threshold', type=float, default=0.75,
                        help='FA threshold to use during fitting')

    parser.add_argument('-out_peaks_dir', type=str, help='filename for peaks direction')

    parser.add_argument('-out_peaks_val', type=str, help='filename for peaks values')

    parser.add_argument('-out_mibrain_peaks', type=str, help='filename for peaks in mibrain format')

    parser.add_argument('-mask', type=str, default=None,
                        help='If provided, only peaks in mask are computed')

    parser.add_argument('-npeaks', type=int, default=5,
                        help='Number of peaks per voxel')

    parser.add_argument('-min_separation', type=float,
                        help='Minimum angle between peaks (0 - 90 degrees)')

    parser.add_argument('-normalize', action='store_true',
                        help='if flag is present peaks are normalized')

    parser.add_argument('-verbose', action='store_true',
                        help='verbose flag')

    args = parser.parse_args()

    csd(args.dwi, args.bvals, args.bvecs,
        args.out_shm, args.roi_center, args.roi_radius, args.fa_threshold,
        args.out_peaks_dir, args.out_peaks_val, args.out_mibrain_peaks,
        args.mask, args.npeaks, args.min_separation, args.normalize,
        args.verbose)
