#!/usr/bin/env python
''' Command Line Interface for ttools_shm_fit '''
import argparse
from tractools.cli.csd_shm import csd_shm

if __name__ == "__main__":

    # Parser
    parser = argparse.ArgumentParser(description=("Computes Spherical "
                                                  "Harmonic coeficients"))

    parser.add_argument('dwi', type=str, help='Diffusion Weighted Image')

    parser.add_argument('bvals', type=str, help='bvals file')

    parser.add_argument('bvecs', type=str, help='bvecs file')

    parser.add_argument('outfile', type=str, help='output file')

    parser.add_argument('-roi_center', type=int, nargs='+', default=None,
                        help='Voxel with strong directionallity, i.e. CC')

    parser.add_argument('-roi_radius', type=int, default=10,
                        help='Radius of sphere around roi_center')

    parser.add_argument('-fa_threshold', type=float, default=0.75,
                        help='FA threshold')

    parser.add_argument('-verbose', action='store_true',
                        help='verbose flag')

    args = parser.parse_args()

    csd_shm(args.dwi, args.bvals, args.bvecs, args.outfile,
            args.roi_center, args.roi_radius, args.fa_threshold,
            args.verbose)
