#!/usr/bin/env python
''' Command Line Interface for tt_tractography '''
import argparse
from tractools.cli.tractography import tractography

if __name__ == "__main__":

    # Parser
    description = ('Performs tracking in parallel. It creates an output file '
                   'per process')
    parser = argparse.ArgumentParser(description=('Performs tracking by '))

    parser.add_argument(dest='shm', type=str,
                        help='Spherical Harmonics file (created with tt_csd)')

    parser.add_argument(dest='mask', type=str,
                        help='tracking mask')

    parser.add_argument(dest='seeds', type=str,
                        help=('txt file with seeds '
                              '(created with tt_seeds_from_labeled_volume)'))

    parser.add_argument(dest='outdir', type=str,
                        help='output directort where to save data')

    parser.add_argument('-algo', dest='algorithm', type=str,
                        choices=['deterministic', 'probabilistic'],
                        default='probabilistic')

    parser.add_argument('-particles', dest='particles', type=int,
                        default=5000, help='number of particles to simulate')

    parser.add_argument('-step_size', dest='step', type=float,
                        default=1, help='step size (mm)')

    parser.add_argument('-max_length', dest='max_len', type=float,
                        default=200, help='maximum length of streamlines (mm)')

    parser.add_argument('-max_angle', dest='max_angle', type=float,
                        default=200, help='maximum length of streamlines (mm)')

    parser.add_argument('-processes', dest='npp', type=int,
                        default=0, help='Number of proccesses to use')

    parser.add_argument('-seeds_per_proc', dest='spp', type=float,
                        help='Number of seeds to compute per process')

    parser.add_argument('-f', action='store_true',
                        help='force overwrite of existing files')

    parser.add_argument('-verbose', action='store_true',
                        help='verbose flag')

    args = parser.parse_args()

    tractography(args.shm, args.mask, args.seeds, args.outdir,
                 args.algorithm, args.particles, args.step,
                 args.max_len, args.max_angle,
                 args.npp, args.spp, args.verbose, args.f)
